adição do metodo de geração de Token
JulioBCP/TechChallenge pull request #11
Opened 2023-10-26 00:45 UTC by LeonardoArantes

2023-10-26 00:58 UTC, victormontibeller requested changes
Revisar o atributo ID nas referências.

2023-10-26 01:12 UTC, victormontibeller approved these changes
Aprovado.

2023-10-27 23:19 UTC, JulioBCP commented on car-rental/src/main/java/com/fiap/techchallenge/carrental/service/CadastroContratoService.java
> +    //update - contrato não tem update
Acho legal apagar essa linha de comentario tbm, ja que nao teremos metodo update

2023-10-27 23:39 UTC, victormontibeller approved these changes
Aprovado.

2023-10-29 13:41 UTC, JulioBCP approved these changes

2023-10-29 13:42 UTC, merged