Precificacao
JulioBCP/TechChallenge pull request #5
Opened 2023-10-24 03:46 UTC by LeonardoArantes

2023-10-24 17:35 UTC, tiagoGermano requested changes

2023-10-24 17:35 UTC, tiagoGermano commented on car-rental/src/main/java/com/fiap/techchallenge/carrental/entity/Reserva.java
> +        if (dataInicio == null && dataFim == null) {
Usar o operador "||" aqui...

2023-10-24 17:35 UTC, tiagoGermano commented on car-rental/src/main/java/com/fiap/techchallenge/carrental/exceptions/CarRentalDateExceptions.java
> +public class CarRentalDateExceptions extends DateTimeException{
Aqui uma **sugestão**... por convenção usar colocar o nome da Exception no singular... "NullPointerExeception", "RuntimeException", "NotFoundException"... etc

2023-10-24 17:35 UTC, tiagoGermano commented on car-rental/src/main/java/com/fiap/techchallenge/carrental/entity/Contrato.java
> +   private Reserva valorContrato;
O tipo está correto ? Não entendi colocar valorContrato como uma Reserva.

2023-10-24 22:37 UTC, LeonardoArantes commented on car-rental/src/main/java/com/fiap/techchallenge/carrental/entity/Reserva.java
> +        if (dataInicio == null && dataFim == null) {
corrigido

2023-10-24 22:39 UTC, LeonardoArantes commented on car-rental/src/main/java/com/fiap/techchallenge/carrental/exceptions/CarRentalDateExceptions.java
> +public class CarRentalDateExceptions extends DateTimeException{
corrigido

2023-10-24 22:48 UTC, LeonardoArantes commented on car-rental/src/main/java/com/fiap/techchallenge/carrental/entity/Contrato.java
> +   private Reserva valorContrato;
corriigido

2023-10-24 22:51 UTC, JulioBCP approved these changes

2023-10-25 13:17 UTC, tiagoGermano approved these changes

2023-10-25 13:30 UTC, merged